language: node_js
node_js:
- 0.1
before_install:
- npm install -g grunt-cli bower
- bower install
before_script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then curl https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash; fi
env:
  global:
  - secure: dVO5M1peBYDTyq1syr9ydPCnREDMBLmav5hS9/ttkf6Ucb1rjYkmGGCU8S7mctYdT8hMKN/FtdjRfD9U/NHQHBddmbOIfb9NSns1q4moS1ythbXUyZ/C//ozjDPuZh2CeAZox0kJ8yFC6UyLaeRA3+qFal0fyMPD+pK85uNb2tM=
  - secure: GUpT/MDWTz4ePjTFe/w4oE3i34wXJ6HFvIFLPe3j1hp/pl4QRElRA8lzFOPXjHtTD8EqTrLEs/RALABm4Md29MAsZUi3yqPvD87O1X94zYghacMvhOQZ3QsqC4/BNTgTWz5XgYepokkK8tNk/p/9u+gHHx74hyxxyl6pTYTk9MY=